local backend = require("lib.backend.sdl2_backend")
backend:init()
local window = backend:create_window("3 Controls Test", 640, 480)
backend:create_button(window, 50, 50, 150, 40, "Button 1")
backend:create_button(window, 220, 50, 150, 40, "Button 2")
backend:create_label(window, 50, 110, 320, 25, "Label 1")
window:render()
backend:run_event_loop(window, {on_close = function() end})
backend:destroy_window(window)
